apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web
  namespace: wordsmith
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  strategy: {}
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: sevrius/wordsmith:web
        name: wordsmith-web
        ports:
        - containerPort: 80
        resources: {}
status: {}
